//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Nosc.Services.Dal.POCOS
{
    public partial class Notificacion
    {
        #region Primitive Properties
    
        public virtual long IdNotificacion
        {
            get;
            set;
        }
    
        public virtual long FechaCreacion
        {
            get;
            set;
        }
    
        public virtual string Parametro
        {
            get;
            set;
        }
    
        public virtual string Mensaje
        {
            get;
            set;
        }
    
        public virtual string Titulo
        {
            get;
            set;
        }
    
        public virtual long IdUsuario
        {
            get { return _idUsuario; }
            set
            {
                if (_idUsuario != value)
                {
                    if (APP_USUARIO != null && APP_USUARIO.IdUsuario != value)
                    {
                        APP_USUARIO = null;
                    }
                    _idUsuario = value;
                }
            }
        }
        private long _idUsuario;
    
        public virtual long IdApp
        {
            get { return _idApp; }
            set
            {
                if (_idApp != value)
                {
                    if (CAT_APP != null && CAT_APP.IdApp != value)
                    {
                        CAT_APP = null;
                    }
                    _idApp = value;
                }
            }
        }
        private long _idApp;
    
        public virtual long FechaNotificacion
        {
            get;
            set;
        }
    
        public virtual bool IsCerrado
        {
            get;
            set;
        }
    
        public virtual Nullable<long> FechaCerrado
        {
            get;
            set;
        }
    
        public virtual bool CanCerrar
        {
            get;
            set;
        }
    
        public virtual bool IsModified
        {
            get;
            set;
        }
    
        public virtual long LastModifiedDate
        {
            get;
            set;
        }
    
        public virtual Nullable<long> ServerLastModifiedDate
        {
            get;
            set;
        }
    
        public virtual int Recurrencia
        {
            get;
            set;
        }
    
        public virtual long FechaUltimaMuestra
        {
            get;
            set;
        }
    
        public virtual bool IsNotificacionActiva
        {
            get;
            set;
        }
    
        public virtual bool IsDescartarOnClick
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual APP_USUARIO APP_USUARIO
        {
            get { return _aPP_USUARIO; }
            set
            {
                if (!ReferenceEquals(_aPP_USUARIO, value))
                {
                    var previousValue = _aPP_USUARIO;
                    _aPP_USUARIO = value;
                    FixupAPP_USUARIO(previousValue);
                }
            }
        }
        private APP_USUARIO _aPP_USUARIO;
    
        public virtual CAT_APP CAT_APP
        {
            get { return _cAT_APP; }
            set
            {
                if (!ReferenceEquals(_cAT_APP, value))
                {
                    var previousValue = _cAT_APP;
                    _cAT_APP = value;
                    FixupCAT_APP(previousValue);
                }
            }
        }
        private CAT_APP _cAT_APP;

        #endregion
        #region Association Fixup
    
        private void FixupAPP_USUARIO(APP_USUARIO previousValue)
        {
            if (previousValue != null && previousValue.Notificacions.Contains(this))
            {
                previousValue.Notificacions.Remove(this);
            }
    
            if (APP_USUARIO != null)
            {
                if (!APP_USUARIO.Notificacions.Contains(this))
                {
                    APP_USUARIO.Notificacions.Add(this);
                }
                if (IdUsuario != APP_USUARIO.IdUsuario)
                {
                    IdUsuario = APP_USUARIO.IdUsuario;
                }
            }
        }
    
        private void FixupCAT_APP(CAT_APP previousValue)
        {
            if (previousValue != null && previousValue.Notificacions.Contains(this))
            {
                previousValue.Notificacions.Remove(this);
            }
    
            if (CAT_APP != null)
            {
                if (!CAT_APP.Notificacions.Contains(this))
                {
                    CAT_APP.Notificacions.Add(this);
                }
                if (IdApp != CAT_APP.IdApp)
                {
                    IdApp = CAT_APP.IdApp;
                }
            }
        }

        #endregion
    }
}
