//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Nosc.DAL
{
    public partial class APP_USUARIO
    {
        #region Primitive Properties
    
        public virtual long IdUsuario
        {
            get;
            set;
        }
    
        public virtual string UsuarioCorreo
        {
            get;
            set;
        }
    
        public virtual string UsuarioPwd
        {
            get;
            set;
        }
    
        public virtual string Nombre
        {
            get;
            set;
        }
    
        public virtual string Apellido
        {
            get;
            set;
        }
    
        public virtual string Area
        {
            get;
            set;
        }
    
        public virtual string Puesto
        {
            get;
            set;
        }
    
        public virtual bool IsActive
        {
            get;
            set;
        }
    
        public virtual bool IsModified
        {
            get;
            set;
        }
    
        public virtual long LastModifiedDate
        {
            get;
            set;
        }
    
        public virtual bool IsNewUser
        {
            get;
            set;
        }
    
        public virtual bool IsVerified
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> IsMailSent
        {
            get;
            set;
        }
    
        public virtual Nullable<long> ServerLastModifiedDate
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<CAT_SESION> CAT_SESION
        {
            get
            {
                if (_cAT_SESION == null)
                {
                    var newCollection = new FixupCollection<CAT_SESION>();
                    newCollection.CollectionChanged += FixupCAT_SESION;
                    _cAT_SESION = newCollection;
                }
                return _cAT_SESION;
            }
            set
            {
                if (!ReferenceEquals(_cAT_SESION, value))
                {
                    var previousValue = _cAT_SESION as FixupCollection<CAT_SESION>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupCAT_SESION;
                    }
                    _cAT_SESION = value;
                    var newValue = value as FixupCollection<CAT_SESION>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupCAT_SESION;
                    }
                }
            }
        }
        private ICollection<CAT_SESION> _cAT_SESION;
    
        public virtual ICollection<Notificacion> Notificacions
        {
            get
            {
                if (_notificacions == null)
                {
                    var newCollection = new FixupCollection<Notificacion>();
                    newCollection.CollectionChanged += FixupNotificacions;
                    _notificacions = newCollection;
                }
                return _notificacions;
            }
            set
            {
                if (!ReferenceEquals(_notificacions, value))
                {
                    var previousValue = _notificacions as FixupCollection<Notificacion>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupNotificacions;
                    }
                    _notificacions = value;
                    var newValue = value as FixupCollection<Notificacion>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupNotificacions;
                    }
                }
            }
        }
        private ICollection<Notificacion> _notificacions;

        #endregion
        #region Association Fixup
    
        private void FixupCAT_SESION(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (CAT_SESION item in e.NewItems)
                {
                    item.APP_USUARIO = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (CAT_SESION item in e.OldItems)
                {
                    if (ReferenceEquals(item.APP_USUARIO, this))
                    {
                        item.APP_USUARIO = null;
                    }
                }
            }
        }
    
        private void FixupNotificacions(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Notificacion item in e.NewItems)
                {
                    item.APP_USUARIO = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Notificacion item in e.OldItems)
                {
                    if (ReferenceEquals(item.APP_USUARIO, this))
                    {
                        item.APP_USUARIO = null;
                    }
                }
            }
        }

        #endregion
    }
}
