//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace Nosc.DAL
{
    public partial class NoscDBEntities : ObjectContext
    {
        public const string ConnectionString = "name=NoscDBEntities";
        public const string ContainerName = "NoscDBEntities";
    
        #region Constructors
    
        public NoscDBEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public NoscDBEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public NoscDBEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<APP_USUARIO> APP_USUARIO
        {
            get { return _aPP_USUARIO  ?? (_aPP_USUARIO = CreateObjectSet<APP_USUARIO>("APP_USUARIO")); }
        }
        private ObjectSet<APP_USUARIO> _aPP_USUARIO;
    
        public ObjectSet<CAT_SESION> CAT_SESION
        {
            get { return _cAT_SESION  ?? (_cAT_SESION = CreateObjectSet<CAT_SESION>("CAT_SESION")); }
        }
        private ObjectSet<CAT_SESION> _cAT_SESION;
    
        public ObjectSet<Notificacion> Notificacions
        {
            get { return _notificacions  ?? (_notificacions = CreateObjectSet<Notificacion>("Notificacions")); }
        }
        private ObjectSet<Notificacion> _notificacions;
    
        public ObjectSet<CAT_APP> CAT_APP
        {
            get { return _cAT_APP  ?? (_cAT_APP = CreateObjectSet<CAT_APP>("CAT_APP")); }
        }
        private ObjectSet<CAT_APP> _cAT_APP;
    
        public ObjectSet<MODIFIEDDATA> MODIFIEDDATA
        {
            get { return _mODIFIEDDATA  ?? (_mODIFIEDDATA = CreateObjectSet<MODIFIEDDATA>("MODIFIEDDATA")); }
        }
        private ObjectSet<MODIFIEDDATA> _mODIFIEDDATA;
    
        public ObjectSet<SYNCTABLE> SYNCTABLE
        {
            get { return _sYNCTABLE  ?? (_sYNCTABLE = CreateObjectSet<SYNCTABLE>("SYNCTABLE")); }
        }
        private ObjectSet<SYNCTABLE> _sYNCTABLE;
    
        public ObjectSet<NOTIFICACION_ACTIVA> NOTIFICACION_ACTIVA
        {
            get { return _nOTIFICACION_ACTIVA  ?? (_nOTIFICACION_ACTIVA = CreateObjectSet<NOTIFICACION_ACTIVA>("NOTIFICACION_ACTIVA")); }
        }
        private ObjectSet<NOTIFICACION_ACTIVA> _nOTIFICACION_ACTIVA;

        #endregion
        #region Function Imports
        public ObjectResult<string> SP_GetMax(string tabla)
        {
    
            ObjectParameter tablaParameter;
    
            if (tabla != null)
            {
                tablaParameter = new ObjectParameter("Tabla", tabla);
            }
            else
            {
                tablaParameter = new ObjectParameter("Tabla", typeof(string));
            }
            return base.ExecuteFunction<string>("SP_GetMax", tablaParameter);
        }
        public ObjectResult<string> SP_GetTableNameModifiedData(string jsonTable)
        {
    
            ObjectParameter jsonTableParameter;
    
            if (jsonTable != null)
            {
                jsonTableParameter = new ObjectParameter("JsonTable", jsonTable);
            }
            else
            {
                jsonTableParameter = new ObjectParameter("JsonTable", typeof(string));
            }
            return base.ExecuteFunction<string>("SP_GetTableNameModifiedData", jsonTableParameter);
        }
        public ObjectResult<string> SP_Upsert_Server_Rows(string json, string nomTbl)
        {
    
            ObjectParameter jsonParameter;
    
            if (json != null)
            {
                jsonParameter = new ObjectParameter("json", json);
            }
            else
            {
                jsonParameter = new ObjectParameter("json", typeof(string));
            }
    
            ObjectParameter nomTblParameter;
    
            if (nomTbl != null)
            {
                nomTblParameter = new ObjectParameter("nomTbl", nomTbl);
            }
            else
            {
                nomTblParameter = new ObjectParameter("nomTbl", typeof(string));
            }
            return base.ExecuteFunction<string>("SP_Upsert_Server_Rows", jsonParameter, nomTblParameter);
        }
        public ObjectResult<string> SP_UpdateModifiedDataLocal(string nomTable, string jsonTableModifiedData)
        {
    
            ObjectParameter nomTableParameter;
    
            if (nomTable != null)
            {
                nomTableParameter = new ObjectParameter("nomTable", nomTable);
            }
            else
            {
                nomTableParameter = new ObjectParameter("nomTable", typeof(string));
            }
    
            ObjectParameter jsonTableModifiedDataParameter;
    
            if (jsonTableModifiedData != null)
            {
                jsonTableModifiedDataParameter = new ObjectParameter("JsonTableModifiedData", jsonTableModifiedData);
            }
            else
            {
                jsonTableModifiedDataParameter = new ObjectParameter("JsonTableModifiedData", typeof(string));
            }
            return base.ExecuteFunction<string>("SP_UpdateModifiedDataLocal", nomTableParameter, jsonTableModifiedDataParameter);
        }
        public ObjectResult<string> SP_TABLE_JSON(string tabla)
        {
    
            ObjectParameter tablaParameter;
    
            if (tabla != null)
            {
                tablaParameter = new ObjectParameter("Tabla", tabla);
            }
            else
            {
                tablaParameter = new ObjectParameter("Tabla", typeof(string));
            }
            return base.ExecuteFunction<string>("SP_TABLE_JSON", tablaParameter);
        }
        public ObjectResult<string> SpConfirmSincRows(string jSON, string nomTbl)
        {
    
            ObjectParameter jSONParameter;
    
            if (jSON != null)
            {
                jSONParameter = new ObjectParameter("JSON", jSON);
            }
            else
            {
                jSONParameter = new ObjectParameter("JSON", typeof(string));
            }
    
            ObjectParameter nomTblParameter;
    
            if (nomTbl != null)
            {
                nomTblParameter = new ObjectParameter("nomTbl", nomTbl);
            }
            else
            {
                nomTblParameter = new ObjectParameter("nomTbl", typeof(string));
            }
            return base.ExecuteFunction<string>("SpConfirmSincRows", jSONParameter, nomTblParameter);
        }

        #endregion
    }
}
