//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Nosc.DAL
{
    public partial class NOTIFICACION_ACTIVA
    {
        #region Primitive Properties
    
        public virtual long IdNotificacionActiva
        {
            get;
            set;
        }
    
        public virtual bool IsActive
        {
            get;
            set;
        }
    
        public virtual long IdNotificacion
        {
            get { return _idNotificacion; }
            set
            {
                if (_idNotificacion != value)
                {
                    if (Notificacion != null && Notificacion.IdNotificacion != value)
                    {
                        Notificacion = null;
                    }
                    _idNotificacion = value;
                }
            }
        }
        private long _idNotificacion;

        #endregion
        #region Navigation Properties
    
        public virtual Notificacion Notificacion
        {
            get { return _notificacion; }
            set
            {
                if (!ReferenceEquals(_notificacion, value))
                {
                    var previousValue = _notificacion;
                    _notificacion = value;
                    FixupNotificacion(previousValue);
                }
            }
        }
        private Notificacion _notificacion;

        #endregion
        #region Association Fixup
    
        private void FixupNotificacion(Notificacion previousValue)
        {
            if (previousValue != null && previousValue.NOTIFICACION_ACTIVA.Contains(this))
            {
                previousValue.NOTIFICACION_ACTIVA.Remove(this);
            }
    
            if (Notificacion != null)
            {
                if (!Notificacion.NOTIFICACION_ACTIVA.Contains(this))
                {
                    Notificacion.NOTIFICACION_ACTIVA.Add(this);
                }
                if (IdNotificacion != Notificacion.IdNotificacion)
                {
                    IdNotificacion = Notificacion.IdNotificacion;
                }
            }
        }

        #endregion
    }
}
